// <auto-generated />
namespace Super_Hero_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SuperHeroes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SuperHeroes));
        
        string IMigrationMetadata.Id
        {
            get { return "201903011937250_SuperHeroes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
